[package]
name = "hass"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = {version = "0.8", optional = true }
thiserror = "1.0.30"
tokio = { version = "1.17", features = ["full"] }
tokio-tungstenite = "0.17"
tracing = { version = "0.1.32", features = ["log"] }
tracing-subscriber = { version = "0.3.9", features = ["registry", "env-filter"] }
tracing-test = "0.2.1"
url = "2.2.2"
#hass-rs = { version = "0.2", features = ["async-std-runtime"] }

[features]
default = []