on: [push]

name: Test

jobs:

  linux_x86_64:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Cargo test
        run: cargo test

  linux_aarch64_musl:
    name: Linux aarch64 MUSL
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add rustup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true
      - name: Cargo test (with cross)
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target aarch64-unknown-linux-musl
