on: [push]

name: Build, Test, and Release

env:
  ARTIFACT_BASENAME: "ha-addon-piresence"
  MODE: "release"

jobs:

  linux_x86_64:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Cargo test
        run: cargo test

  cross_build:
    name: Cross Build (${{ matrix.target.arch }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - {arch: x86_64, cargo: x86_64-unknown-linux-gnu}
          - {arch: aarch64, cargo: aarch64-unknown-linux-musl}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Add rustup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target.cargo }}
          override: true
      - name: Cargo test (with cross)
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: test
          args: --target ${{ matrix.target.cargo }} --${{ MODE }}
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target.arch }}-${{ ARTIFACT_BASENAME }}
          path: target/${{ matrix.target.cargo }}/${{ MODE }}/${{ ARTIFACT_BASENAME }}